import type {Metadata} from "next";
import Script from "next/script";
import type {ReactNode} from "react";
import "@/app/styles/_index.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
    <Script src="https://telegram.org/js/telegram-web-app.js"/>
    <body>{children}</body>
    </html>
  );
}
