export enum EFormFields {
  DisplayName = "displayName",
  Email = "email",
  MobileNumber = "mobileNumber",
  Password = "password",
  PasswordConfirm = "passwordConfirm",
  Birthday = "birthday",
  Gender = "gender",
  SearchGender = "searchGender",
  Location = "location",
  Description = "description",
  Height = "height",
  Weight = "weight",
  LookingFor = "lookingFor",
  Image = "image",
  TelegramID = "telegramId",
  Username = "userName",
  FirstName = "firstName",
  LastName = "lastName",
  LanguageCode = "languageCode",
  AllowsWriteToPm = "allowsWriteToPm",
  QueryId = "queryId",
  Latitude = "latitude",
  Longitude = "longitude",
}
