export enum EFormFields {
  AllowsWriteToPm = "allowsWriteToPm",
  Birthday = "birthday",
  Description = "description",
  DisplayName = "displayName",
  FirstName = "firstName",
  Gender = "gender",
  Image = "image",
  LanguageCode = "languageCode",
  LastName = "lastName",
  Location = "location",
  TelegramID = "telegramId",
  QueryId = "queryId",
  Username = "username",
}
