export enum EFormFields {
  Id = "id",
  DisplayName = "displayName",
  Birthday = "birthday",
  Gender = "gender",
  SearchGender = "searchGender",
  Location = "location",
  Description = "description",
  Height = "height",
  Weight = "weight",
  LookingFor = "lookingFor",
  IsDefaultImage = "isDefaultImage",
  Image = "image",
  TelegramID = "telegramId",
  Username = "username",
  FirstName = "firstName",
  LastName = "lastName",
  LanguageCode = "languageCode",
  AllowsWriteToPm = "allowsWriteToPm",
  QueryId = "queryId",
  Latitude = "latitude",
  Longitude = "longitude",
}
